### ISSUE TITLE
SIGFPE tests fail with -O2 and LTO

### ISSUE THREAD

**Issue by qsuscs** [textshell/posixsignalmanager#4]
On Fedora, builds default to using LTO.  This causes the SIGFPE tests to fail at least on x86_64 (notably, without LTO, all tests pass):

```
NSIG: 65, SIGRTMAX: 64
Randomness seeded to: 1222419932

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests is a Catch2 v3.4.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
baseline sigfpe
-------------------------------------------------------------------------------
../tests/tests.cpp:982
...............................................................................

../tests/tests.cpp:988: FAILED:
  CHECK( info._sifields._sigchld.si_status == 8 )
with expansion:
  4 == 8

===============================================================================
test cases:   40 |   39 passed | 1 failed
assertions: 1158 | 1157 passed | 1 failed
```

Steps to reproduce:

```sh
podman run --rm -ti registry.fedoraproject.org/fedora:39
dnf install git meson gcc-c++ 'pkgconfig(catch2)' 'pkgconfig(Qt5Core)'
cd /tmp
git clone https://github.com/textshell/posixsignalmanager
cd posixsignalmanager
git checkout 96409f2726b59eb82b2b25419a39b0152f6d4bfe
CXXFLAGS='-O2 -flto=auto -ffat-lto-objects' meson setup _build --buildtype=plain -Dsystem-catch2=enabled
cd _build
ninja test
```

I could also reproduce this with Ubuntu 23.10 (GCC 13 as well) and Debian 12 (GCC 12), so this does not seem to be a Fedora-specific issue.  Also, similar (though in detail slightly different) test failures occur with Clang and LTO.

This does not occur with #1 merged, even though that one is intended for non-x86 platforms.  I currently do not have any hardware to test other platforms available.

**Comment by textshell** [comment]
Yes, the tests are a lot of cat and mouse with the compiler because they are testing what happens on various kinds of crashes. But of course a program not invoking undefined behavior doesn't crash.

The PR for better multi platform support might have something helpful to avoid the compiler removing the needed crashes.
But to make sure i have now extended the meson build script to (for the tests only) disable link time optimization and generally optimization as well.

This seems to help to get things to compile with the flags used in a fedora container for building rpm.

I've not merged the multi platform support fixes, so hopefully this issue can be closed now.

If to discovery further issues please reopen this issue or open a new one.
